[package]
name = "talkops-provisioning"
description = "Yealink auto-provisioning, XML phonebook and firmware management"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
minijinja = "2.24.0"
serde = { workspace = true, features = ["derive"] }
serde_yaml_ng = "0.10.0"
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
serde_json.workspace = true
