//! Generation of FreeSWITCH XML for `mod_xml_curl` (ADR 0006).
//!
//! FreeSWITCH asks for three sections:
//! - `configuration`: module configs, here `sofia.conf` (SIP profiles + trunk gateways)
//! - `directory`: SIP users (devices) for authentication and bridging
//! - `dialplan`: one generated extension per call, routing decided in Rust

pub mod cdr;
pub mod dialplan;
pub mod directory;
pub mod sofia;

use std::fmt::Write;

/// Fixed SIP domain all device registrations are stored under, independent
/// of the host name or IP the phones were configured with.
pub const SIP_DOMAIN: &str = "talkops.local";

/// Context for calls from registered devices.
pub const CONTEXT_INTERNAL: &str = "internal";
/// Context for calls arriving from trunks.
pub const CONTEXT_PUBLIC: &str = "public";
/// Transfers from TalkOps applications (IVR choices) to a destination;
/// never assigned to incoming calls, so callers cannot select it.
pub const CONTEXT_TRANSFER: &str = "talkops";

pub const NOT_FOUND: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document type="freeswitch/xml">
  <section name="result">
    <result status="not found"/>
  </section>
</document>
"#;

/// Escapes a value for use in an XML attribute or text node.
pub fn esc(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            // FreeSWITCH's preprocessor expands $${…}; never let data trigger it.
            '$' => out.push_str("&#36;"),
            c if (c as u32) < 0x20 && c != '\t' => {}
            c => out.push(c),
        }
    }
    out
}

/// Removes characters that FreeSWITCH interprets inside application data or
/// dial strings (variable expansion `${…}`/API calls, channel variable blocks
/// `{…}`/`[…]`, dial string separators). Applied to every value that is not
/// fully controlled by TalkOps, such as display names or caller numbers.
pub fn sanitize_value(value: &str) -> String {
    value
        .chars()
        .filter(|c| {
            !matches!(
                c,
                '$' | '{' | '}' | '[' | ']' | '^' | ',' | '|' | '\'' | '"' | '\\' | '<' | '>' | '&'
            )
        })
        .filter(|c| !c.is_control())
        .take(80)
        .collect::<String>()
        .trim()
        .to_owned()
}

/// Minimal XML writer producing indented FreeSWITCH documents.
#[derive(Default)]
pub struct XmlWriter {
    buf: String,
    depth: usize,
}

impl XmlWriter {
    pub fn document() -> Self {
        let mut w = Self::default();
        w.buf
            .push_str("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n");
        w.open("document", &[("type", "freeswitch/xml")]);
        w
    }

    fn indent(&mut self) {
        for _ in 0..self.depth {
            self.buf.push_str("  ");
        }
    }

    fn attrs(&mut self, attrs: &[(&str, &str)]) {
        for (k, v) in attrs {
            let _ = write!(self.buf, " {k}=\"{}\"", esc(v));
        }
    }

    pub fn open(&mut self, tag: &str, attrs: &[(&str, &str)]) {
        self.indent();
        self.buf.push('<');
        self.buf.push_str(tag);
        self.attrs(attrs);
        self.buf.push_str(">\n");
        self.depth += 1;
    }

    pub fn close(&mut self, tag: &str) {
        self.depth -= 1;
        self.indent();
        let _ = writeln!(self.buf, "</{tag}>");
    }

    pub fn empty(&mut self, tag: &str, attrs: &[(&str, &str)]) {
        self.indent();
        self.buf.push('<');
        self.buf.push_str(tag);
        self.attrs(attrs);
        self.buf.push_str("/>\n");
    }

    pub fn param(&mut self, name: &str, value: &str) {
        self.empty("param", &[("name", name), ("value", value)]);
    }

    /// Writes a param whose value may contain FreeSWITCH variables (`$${…}`,
    /// `${…}`) generated by TalkOps itself. Only `"`, `<`, `&` are escaped.
    pub fn raw_param(&mut self, name: &str, value: &str) {
        self.indent();
        let value = value
            .replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('"', "&quot;");
        let _ = writeln!(
            self.buf,
            "<param name=\"{}\" value=\"{value}\"/>",
            esc(name)
        );
    }

    pub fn finish(mut self) -> String {
        self.close("document");
        self.buf
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_xml_and_variable_syntax() {
        assert_eq!(
            esc(r#"a&b<c>"d'$${x}"#),
            "a&amp;b&lt;c&gt;&quot;d&apos;&#36;&#36;{x}"
        );
        assert_eq!(esc("ok\u{1}"), "ok");
    }

    #[test]
    fn sanitizes_untrusted_values() {
        assert_eq!(
            sanitize_value("Müller ${system(rm -rf /)}"),
            "Müller system(rm -rf /)"
        );
        assert_eq!(sanitize_value("a,b|c^d[e]{f}"), "abcdef");
        assert_eq!(sanitize_value(&"x".repeat(200)).len(), 80);
    }

    #[test]
    fn writes_nested_document() {
        let mut w = XmlWriter::document();
        w.open("section", &[("name", "dialplan")]);
        w.param("x", "1");
        w.close("section");
        let xml = w.finish();
        roxmltree::Document::parse(&xml).unwrap();
        assert!(xml.contains("<param name=\"x\" value=\"1\"/>"));
    }
}
